# Generated by Django 3.1.2 on 2020-10-06 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 11, 49, 31, 58775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
